apiVersion: v1
kind: Service
metadata:
  name: skyvern-backend
  namespace: skyvern
spec:
  type: ClusterIP # Or LoadBalancer
  ports:
    - name: http
      port: 28743
      targetPort: 28743
    - name: cdp
      port: 9222
      targetPort: 9222
  selector:
    app: skyvern-backend
